### PR TITLE
Hand off all arguments supplied to the breaker callback.

### PR DESCRIPTION
**Pull request by crueber**
@dmuth It would be really helpful if I could have all the supplied arguments from the breaker function handed in to the final function. That's what this code supports. I'm hoping you'll be willing to pull it in and push it up to npm with a minor version nudge!

### CODE REVIEW

**Comment by dmuth** [comment]
Sure, happy to!

It's been ages since I did anything in npm, I might need to get back up to speed on pushing it to NPM...

**Comment by crueber** [comment]
If you go to your project root, pull it all in, type `npm version minor` and `npm publish`, assuming you're logged in, that should about do it! It's pretty painless... :)

**Comment by dmuth** [comment]
Whoa, that seemed to have worked on the very first try:

```
[Cheetah-Collector:~/development/node/circuitbreaker-demo ] $ npm publish
+ another-circuit-breaker@0.3.4
```

Let me know if I screwed it up. :-)

Thanks,

-- Doug

**Comment by crueber** [comment]
I just checked. Looks great! Thanks very much!

**Comment by dmuth** [comment]
Also, thanks for the tip with `npm version`. :+1:   I just updated the package.json by hand.  Silly me. :-)

**Pull request merged**
